import Head from 'next/head'
import Image from 'next/image'
import ChatImg from '../assets/chat.svg'
import {
  AllWalletWrapper,
  BalanceText,
  FirstRow,
  MainContainer,
  MainContent,
  MainWrapper,
  NewWalletIcon,
  NewWalletText,
  NewWalletWrapper,
  PaymentAction,
  PaymentContent,
  PaymentDiv,
  PaymentText,
  TitleContainer,
  TitleDiv,
  TopDiv,
  WalletCardRow,
  WalletDescription,
  WalletHeader,
  WalletInfo,
  WalletInfoTitle,
  WalletInfoTitleText,
  WalletProgressStatusWrapper,
  WalletTitleDiv,
  WalletWrapper,
} from '@/styles/pages'
import SideBarComponent from '@/styles/components/sidebar'

export default function Home() {
  return (
    <>
      <Head>
        <title>Bongo Finance</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <MainWrapper>
        <SideBarComponent />
        <MainContainer>
          <TopDiv></TopDiv>
          <TitleContainer>
            <TitleDiv>
              <h1>Carteira</h1>
              <span>Sua vida financeira em dia</span>
            </TitleDiv>
          </TitleContainer>
          <MainContent>
            <FirstRow>
              <WalletInfo>
                <WalletInfoTitle>
                  <Image src={ChatImg} alt='Chat' width={30} height={30} />
                  <WalletInfoTitleText>
                    Olá, Eduardo Ayr Goulart
                  </WalletInfoTitleText>
                </WalletInfoTitle>
                <BalanceText>R$ 14,424</BalanceText>
              </WalletInfo>
              <PaymentAction>
                <PaymentDiv>
                  <PaymentContent>
                    <Image src={ChatImg} alt='Chat' width={30} height={30} />
                    <PaymentText>Transferir</PaymentText>
                  </PaymentContent>
                </PaymentDiv>
                <PaymentDiv>
                  <PaymentContent>
                    <Image src={ChatImg} alt='Chat' width={30} height={30} />
                    <PaymentText>Pagar</PaymentText>
                  </PaymentContent>
                </PaymentDiv>
              </PaymentAction>
            </FirstRow>
            <AllWalletWrapper>
              <WalletCardRow>
                <WalletWrapper>
                  <WalletHeader>
                    <WalletTitleDiv>Imagem TITULO</WalletTitleDiv>
                    <WalletDescription>DESCRIÇÃO</WalletDescription>
                  </WalletHeader>
                  <WalletProgressStatusWrapper>
                    status bar
                  </WalletProgressStatusWrapper>
                </WalletWrapper>
                <WalletWrapper>
                  <WalletHeader>
                    <WalletTitleDiv>Imagem TITULO</WalletTitleDiv>
                    <WalletDescription>DESCRIÇÃO</WalletDescription>
                  </WalletHeader>
                  <WalletProgressStatusWrapper>
                    status bar
                  </WalletProgressStatusWrapper>
                </WalletWrapper>
                <WalletWrapper>
                  <WalletHeader>
                    <WalletTitleDiv>Imagem TITULO</WalletTitleDiv>
                    <WalletDescription>DESCRIÇÃO</WalletDescription>
                  </WalletHeader>
                  <WalletProgressStatusWrapper>
                    status bar
                  </WalletProgressStatusWrapper>
                </WalletWrapper>
              </WalletCardRow>
              <WalletCardRow>
                <WalletWrapper>
                  <WalletHeader>
                    <WalletTitleDiv>Imagem TITULO</WalletTitleDiv>
                    <WalletDescription>DESCRIÇÃO</WalletDescription>
                  </WalletHeader>
                  <WalletProgressStatusWrapper>
                    status bar
                  </WalletProgressStatusWrapper>
                </WalletWrapper>
                <WalletWrapper>
                  <WalletHeader>
                    <WalletTitleDiv>Imagem TITULO</WalletTitleDiv>
                    <WalletDescription>DESCRIÇÃO</WalletDescription>
                  </WalletHeader>
                  <WalletProgressStatusWrapper>
                    status bar
                  </WalletProgressStatusWrapper>
                </WalletWrapper>
                <WalletWrapper>
                  <WalletHeader>
                    <WalletTitleDiv>Imagem TITULO</WalletTitleDiv>
                    <WalletDescription>DESCRIÇÃO</WalletDescription>
                  </WalletHeader>
                  <WalletProgressStatusWrapper>
                    status bar
                  </WalletProgressStatusWrapper>
                </WalletWrapper>
              </WalletCardRow>
              <NewWalletWrapper>
                <NewWalletIcon>+</NewWalletIcon>
                <NewWalletText>Criar Nova Carteira</NewWalletText>
              </NewWalletWrapper>
            </AllWalletWrapper>
          </MainContent>
        </MainContainer>
      </MainWrapper>
    </>
  )
}
