import {
  LogoWrapper,
  MenuItemText,
  MenuItemWrapper,
  MenuItemsContainer,
  MenuItemsWrapper,
  MenuSettingsWrapper,
  SideBar,
} from '@/styles/components/sidebar'
import Head from 'next/head'
import Image from 'next/image'
import LogoImg from '../assets/logo.png'
import ChatImg from '../assets/chat.svg'
import {
  BalanceText,
  FirstRow,
  MainContainer,
  MainContent,
  MainWrapper,
  PaymentAction,
  PaymentContent,
  PaymentDiv,
  PaymentText,
  TitleContainer,
  TitleDiv,
  TopDiv,
  WalletInfo,
  WalletInfoTitle,
  WalletInfoTitleText,
} from '@/styles/pages'

export default function Home() {
  return (
    <>
      <Head>
        <title>Bongo Finance</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <MainWrapper>
        <SideBar>
          <MenuItemsWrapper>
            <LogoWrapper>
              <Image src={LogoImg} alt='Bongo Finance' width={80} height={80} />
            </LogoWrapper>
            <MenuItemsContainer>
              <MenuItemWrapper>
                <Image src={ChatImg} alt='Chat' width={30} height={30} />
                <MenuItemText>Carteira</MenuItemText>
              </MenuItemWrapper>
              <MenuItemWrapper>
                <Image src={ChatImg} alt='Chat' width={30} height={30} />
                <MenuItemText>Cartões</MenuItemText>
              </MenuItemWrapper>
              <MenuItemWrapper>
                <Image src={ChatImg} alt='Chat' width={30} height={30} />
                <MenuItemText>Transações</MenuItemText>
              </MenuItemWrapper>
            </MenuItemsContainer>
          </MenuItemsWrapper>
          <MenuSettingsWrapper>
            <MenuItemWrapper>
              <Image src={ChatImg} alt='Chat' width={30} height={30} />
              <MenuItemText>Configurações</MenuItemText>
            </MenuItemWrapper>
            <MenuItemWrapper>
              <Image src={ChatImg} alt='Chat' width={30} height={30} />
              <MenuItemText>Eduardo Ayr</MenuItemText>
            </MenuItemWrapper>
          </MenuSettingsWrapper>
        </SideBar>
        <MainContainer>
          <TopDiv></TopDiv>
          <TitleContainer>
            <TitleDiv>
              <h1>Carteira</h1>
              <span>Sua vida financeira em dia</span>
            </TitleDiv>
          </TitleContainer>
          <MainContent>
            <FirstRow>
              <WalletInfo>
                <WalletInfoTitle>
                  <Image src={ChatImg} alt='Chat' width={30} height={30} />
                  <WalletInfoTitleText>
                    Olá, Eduardo Ayr Goulart
                  </WalletInfoTitleText>
                </WalletInfoTitle>
                <BalanceText>R$ 14,424</BalanceText>
              </WalletInfo>
              <PaymentAction>
                <PaymentDiv>
                  <PaymentContent>
                    <Image src={ChatImg} alt='Chat' width={30} height={30} />
                    <PaymentText>Transferir</PaymentText>
                  </PaymentContent>
                </PaymentDiv>
                <PaymentDiv>
                  <PaymentContent>
                    <Image src={ChatImg} alt='Chat' width={30} height={30} />
                    <PaymentText>Pagar</PaymentText>
                  </PaymentContent>
                </PaymentDiv>
              </PaymentAction>
            </FirstRow>
          </MainContent>
        </MainContainer>
      </MainWrapper>
    </>
  )
}
